//go:build !windows
// +build !windows

package main

import (
	"os"
	"syscall"
	"time"
)

// drainStdin discards any bytes currently pending in stdin (e.g., cursor-position
// report responses generated by survey's raw-mode rendering).
// It briefly sets stdin non-blocking, reads and discards pending data, then
// resets the shared bufio reader so no stale bytes remain.
func drainStdin() {
	// Poll until stdin is quiet for a full 80ms window.
	// 30ms was not enough after 3+ consecutive survey.Select calls — leftover
	// CPR responses (\033[row;colR) were arriving late and being consumed as
	// user input by the next readLine or surveySelect.
	fd := int(os.Stdin.Fd())
	if err := syscall.SetNonblock(fd, true); err != nil {
		stdinReader.Reset(os.Stdin)
		return
	}
	defer func() {
		_ = syscall.SetNonblock(fd, false)
		stdinReader.Reset(os.Stdin)
	}()

	buf := make([]byte, 256)
	deadline := time.Now().Add(80 * time.Millisecond)
	for time.Now().Before(deadline) {
		n, err := syscall.Read(fd, buf)
		if n > 0 {
			// drained some bytes — reset deadline, keep going
			deadline = time.Now().Add(80 * time.Millisecond)
			continue
		}
		if err == syscall.EAGAIN || err == syscall.EWOULDBLOCK {
			time.Sleep(10 * time.Millisecond)
			continue
		}
		break
	}
}
